### ISSUE TITLE
Reset image view when changing selection

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium#124]
The zoom level of the image plot is unchanged when a new selection is made, which feels weird. It should be reset to the full field of view.

**Comment by jni** [comment]
the main problem is that the "real" zoom level is dependent on how many images you've selected. So if you select one image, zoom in to the center, then select four images, now you're staring at the corner of the four images (mostly blank). Or worse, if you select four images, zoom in to the top right one, then select three images, suddenly you're looking at blank space. After exploring around with Iva and Sarah, I really think I was hitting reset *way more* than I was happy with the zoom where it was. Anyway, once I get you the full dataset you can play around and see if you still feel the same way.

**Comment by GenevieveBuckley** [comment]
Ah ok, I'll have a play with it and will probably retract my objection then.

**Comment by GenevieveBuckley** [comment]
I've just been having a go at this using the suggestions from PR https://github.com/bokeh/bokeh/pull/7757
The example as written works well, but I couldn't successfully add: 
```python
CustomJS(args=dict(p=image_plot), code="""p.reset.emit()""")
```
as a line in our `load_selected` python update function.

Adding an extra `source.selected.on_change()` line results in an error, since there is no selection existing initially.

Example (https://github.com/bokeh/bokeh/pull/7757):
```python
from bokeh.io import show
from bokeh.layouts import column
from bokeh.models import Button, CustomJS
from bokeh.plotting import figure

p = figure(tools="reset,pan,wheel_zoom,lasso_select")
p.circle(list(range(10)), list(range(10)))

b = Button()
b.js_on_click(CustomJS(args=dict(p=p), code="""
    p.reset.emit()
"""))

show(column(p, b))
```
