### ISSUE TITLE
Figure out mongo sample _id

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium#53]
The current schema is `<screen>-<plate>-<well>`. I'm unsatisfied with this because displaying `<screen>` on every sample, when a researcher can only (and probably will only) investigate a single screen at a time is both redundant and obnoxious. Even further, while we can reasonably guarantee that the `<plate>-<well>` ID is unique _within_ a screen, we can be pretty certain that we _can't_ guarantee that screen names will be unique, at which point the whole `_id` becomes problematic.

Possible solutions:
- just use `<plate>-<well>` and hope for the best
- use mongo-assigned `_id`s and then search by screen/plate-well combinations. (possibly slower?)
- other?

**Comment by starcalibre** [comment]
ObjectID (a 12-byte BSON) is the best way to do it -- smaller indices and faster to query. A incrementing integer is even faster (it's smaller), but I prefer the ObjectID because it's generated automatically and guaranteed to be unique. We're not dealing with datasets sized in the billions here, so it's fine to go for the safer and easier option.

Right now, the ``<screen>-<plate>-<well>`` _id is already being used as the primary key -- so replacing these with UUIDs would be no problem.

Any titles can just be rendered by combining the ``plate`` and ``well`` information from the data.

**Comment by starcalibre** [comment]
Just confirm what we discussed on the tram, the sample field will have the following fields:
```

{ _id:  // A Mongo generated ObjectID
screen: // The screen
plate: // Plate ID
row: // column
column: // well }

I think that the current ``well`` field is completely redundant, so I say get rid of it. And it's best to keep all our columns atomic anyway.

In the UI, samples can be found either by searching the ``_id`` primary key, or by creating a composite index on ``(sample, plate, row, column)``

**Comment by jni** [comment]
I agree about atomicity, but I much prefer plate-well to plate-row-col. It's a Pythonic thing: flat is better than nested.

Anyway, let me think about it. Part of my resistance is because soooo much of the code depends on plate-well.

**Comment by GenevieveBuckley** [comment]
Since mongo has been removed (see https://github.com/microscopium/microscopium/pull/157) this issue is now outdated and no longer relevant.
